### ISSUE TITLE
Development Roadmap

### ISSUE THREAD

**Issue by arkypita** [arkypita/LaserGRBL#64]
[Lastest Release](https://github.com/arkypita/LaserGRBL/releases)

Planned developments for LaserGRBL are:
- [ ] Made both raster vectorization and filling using absolute coordinate
- [ ] Pen-up pen-down for GRBL plotter #42 
- [ ] Centerline tracing with autotrace
- [ ] Non-linear color to power conversion, and numbers of colour optimization #27
- [ ] SVG Import, with multi-layer configuration #29 
- [ ] PLT/DXF Import, with multi-layer configuration
- [ ] More GCode optimization with vectorization (split black paths, sort, and mark them individually)

New feature request can be posted as "[new issue](https://github.com/arkypita/LaserGRBL/issues/new)" and they will be examined.

Development and support may suffer from slowdowns in july and august due holidays :-)
